# Generated by Django 5.2.7 on 2025-10-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_userdetails_bio_userdetails_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
